key: VerySecureKey
users:
  test:
    - J00LZZ
    - Invalid user
    - Someone else
allow_update: true
pgp_public_key: |
  -----BEGIN PGP PUBLIC KEY BLOCK-----

  mDMEYX1r0xYJKwYBBAHaRw8BAQdAE/ACWGeKilogklgi2GzRgT7DqU9sruda7X3e
  lv7Cr9C0MEtleWxvbWV0ZXIgKEtleWxvbWV0ZXIpIDxrZXlsb21ldGVyQHZvaWRj
  b3JwLm5sPoiQBBMWCAA4FiEEPpV7+C2jrPYTWv95NqnU65JHzfMFAmF9a9MCGwMF
  CwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQNqnU65JHzfMGCwD+LhpV7DdO55Ai
  IaPkJ8B2MlscMGUxllQE01IP1mk1t+4A/1ai92SW5r8y29UHPU0GjZYxb9oN95EM
  dnY181uAdVIKuDgEYX1r0xIKKwYBBAGXVQEFAQEHQHrNVUSLnmjpFZRoHtTcGteP
  2QYPAlg6g2zkFKT0R/cuAwEIB4h4BBgWCAAgFiEEPpV7+C2jrPYTWv95NqnU65JH
  zfMFAmF9a9MCGwwACgkQNqnU65JHzfOmbgEA6Y2TPLmujhN0XQZIzbgfc41yd94z
  dOollWUpRanTHAAA/27xKb3Hbj1f6lOe6wmYMQeIivY8600ZcHRocSJHppoE
  =/UoU
  -----END PGP PUBLIC KEY BLOCK-----